services:
  # -----------------------
  # PostgreSQL Database
  # -----------------------
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # optional: initial SQL scripts

  # -----------------------
  # Redis Cache
  # -----------------------
  redis:
    image: redis:8-alpine
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data

  # -----------------------
  # pgAdmin
  # -----------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: chimbo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

volumes:
  pgdata:
  redisdata:
